-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-03-15 19:48:36 CDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Category 
    ( 
     category_id NUMBER,
     category_name        VARCHAR2(100),
     category_description VARCHAR2(500)
                    
    ) 
;

ALTER TABLE Category 
    ADD CONSTRAINT Category_category_id_UN UNIQUE ( category_id ) ;
    
CREATE TABLE Element 
    ( 
     atomic_number        NUMBER 
                     NOT NULL , -- primary key
     element_name         VARCHAR2(100) 
                    , 
     symbol               VARCHAR2(10) 
                    , 
     atomic_mass          NUMBER 
                    , 
     -- period               NUMBER 
     --                , 
     group_number         NUMBER -- groups indicate the vertical column
                    , 
     group_name           VARCHAR2(100)
                    , 
     Category_category_id NUMBER -- this is a foreign key
                     NOT NULL , -- references Category table category_id column
     Period_period_id     NUMBER -- this is a foreign key
                     NOT NULL -- references Period table period_id column
    ) 
;

ALTER TABLE Element 
    ADD CONSTRAINT Element_PK PRIMARY KEY ( atomic_number ) ;
    
/* Period indicates the sequential filling of each electron orbital.
   Electrons fill from the lowest energy levels to highest ones.
   Elements in a Period have the same number of electron shells. */
CREATE TABLE Period -- horizontal rows
    ( 
     period_id NUMBER 
                    ,
     number_of_electrons NUMBER -- number of electrons that occupy that period
    ) 
;

ALTER TABLE Period 
    ADD CONSTRAINT Period_period_id_UN UNIQUE ( period_id ) ;
    
ALTER TABLE Element 
    ADD CONSTRAINT Element_Category_FK FOREIGN KEY 
    ( 
     Category_category_id
    ) 
    REFERENCES Category 
    ( 
     category_id
    ) 
;

ALTER TABLE Element 
    ADD CONSTRAINT Element_Period_FK FOREIGN KEY 
    ( 
     Period_period_id
    ) 
    REFERENCES Period 
    ( 
     period_id
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                  11
-- WARNINGS                                 0

INSERT INTO Category VALUES (1, 'Metal', 'Lustrous, malleable, and conductive of heat and electricity');
INSERT INTO Category VALUES (2, 'Non-metal', 'Poor conductor of heat and electricity, often gaseous or brittle in solid form');
INSERT INTO Category VALUES (3, 'Metalloid', 'Intermediate properties between metals and non-metals, semiconductive in nature');

INSERT INTO Period VALUES (1, 2);
INSERT INTO Period VALUES (2, 8);
INSERT INTO Period VALUES (3, 8);
INSERT INTO Period VALUES (4, 18);
INSERT INTO Period VALUES (5, 18);
INSERT INTO Period VALUES (6, 32);
INSERT INTO Period VALUES (7, 32);

/* Used Claude for defining data in these INSERT statements, 
   then I double checked the data for myself. */

-- atomic_number, element_name, symbol, atomic_mass, group_number (i.e. column),
-- group_name, Category_category_id, Period_period_id
INSERT INTO Element VALUES (1, 'Hydrogen', 'H', 1.008, 1, 'Alkali metal', 2, 1);
-- Claude falsely listed group name for category identification
INSERT INTO Element VALUES (2, 'Helium', 'He', 4.003, 18, 'Noble gas', 2, 1);
INSERT INTO Element VALUES (3, 'Lithium', 'Li', 6.941, 1, 'Alkali metal', 1, 2);
INSERT INTO Element VALUES (4, 'Beryllium', 'Be', 9.012, 2, 'Alkaline earth metal', 1, 2);
INSERT INTO Element VALUES (5, 'Boron', 'B', 10.811, 13, 'Boron group, or, earth metal', 3, 2);
INSERT INTO Element VALUES (6, 'Carbon', 'C', 12.011, 14, 'Carbon group, or, tetrel', 2, 2);
INSERT INTO Element VALUES (7, 'Nitrogen', 'N', 14.007, 15, 'Nitrogen group, or, pnictogen', 2, 2);
INSERT INTO Element VALUES (8, 'Oxygen', 'O', 15.999, 16, 'Oxygen group, or, chalcogen', 2, 2);
INSERT INTO Element VALUES (9, 'Fluorine', 'F', 18.998, 17, 'Halogen', 2, 2);
-- Claude falsely listed group name for category identification
INSERT INTO Element VALUES (10, 'Neon', 'Ne', 20.180, 18, 'Noble gas', 2, 2);
INSERT INTO Element VALUES (11, 'Sodium', 'Na', 22.990, 1, 'Alkali metal', 1, 3);
INSERT INTO Element VALUES (12, 'Magnesium', 'Mg', 24.305, 2, 'Alkaline earth metal', 1, 3);
INSERT INTO Element VALUES (13, 'Aluminum', 'Al', 26.982, 13, 'Boron group, or, earth metal', 1, 3);
INSERT INTO Element VALUES (14, 'Silicon', 'Si', 28.086, 14, 'Carbon group, or, tetrel', 3, 3);
INSERT INTO Element VALUES (15, 'Phosphorus', 'P', 30.974, 15, 'Nitrogen group, or, pnictogen', 2, 3);
-- Claude put 32.065 for the atomic mass for sulfur
INSERT INTO Element VALUES (16, 'Sulfur', 'S', 32.066, 16, 'Oxygen group, or, chalcogen', 2, 3);
INSERT INTO Element VALUES (17, 'Chlorine', 'Cl', 35.453, 17, 'Halogen', 2, 3);
-- Claude falsely listed group name for category identification
INSERT INTO Element VALUES (18, 'Argon', 'Ar', 39.948, 18, 'Noble gas', 2, 3);
INSERT INTO Element VALUES (19, 'Potassium', 'K', 39.098, 1, 'Alkali metal', 1, 4);
INSERT INTO Element VALUES (20, 'Calcium', 'Ca', 40.078, 2, 'Alkaline earth metal', 1, 4);
INSERT INTO Element VALUES (21, 'Scandium', 'Sc', 44.956, 3, 'Transition metal', 1, 4);
INSERT INTO Element VALUES (22, 'Titanium', 'Ti', 47.867, 4, 'Transition metal', 1, 4);
INSERT INTO Element VALUES (23, 'Vanadium', 'V', 50.942, 5, 'Transition metal', 1, 4);
INSERT INTO Element VALUES (24, 'Chromium', 'Cr', 51.996, 6, 'Transition metal', 1, 4);
INSERT INTO Element VALUES (25, 'Manganese', 'Mn', 54.938, 7, 'Transition metal', 1, 4);
INSERT INTO Element VALUES (26, 'Iron', 'Fe', 55.845, 8, 'Transition metal', 1, 4);
INSERT INTO Element VALUES (27, 'Cobalt', 'Co', 58.933, 9, 'Transition metal', 1, 4);
INSERT INTO Element VALUES (28, 'Nickel', 'Ni', 58.693, 10, 'Transition metal', 1, 4);
INSERT INTO Element VALUES (29, 'Copper', 'Cu', 63.546, 11, 'Transition metal', 1, 4);
INSERT INTO Element VALUES (30, 'Zinc', 'Zn', 65.38, 12, 'Transition metal', 1, 4);
INSERT INTO Element VALUES (31, 'Gallium', 'Ga', 69.723, 13, 'Boron group, or, earth metal', 1, 4);
-- Claude put 72.630 for the atomic mass for Germanium
INSERT INTO Element VALUES (32, 'Germanium', 'Ge', 72.631, 14, 'Carbon group, or, tetrel', 3, 4);
INSERT INTO Element VALUES (33, 'Arsenic', 'As', 74.922, 15, 'Nitrogen group, or, pnictogen', 3, 4);
INSERT INTO Element VALUES (34, 'Selenium', 'Se', 78.971, 16, 'Oxygen group, or, chalcogen', 2, 4);
INSERT INTO Element VALUES (35, 'Bromine', 'Br', 79.904, 17, 'Halogen', 2, 4);
-- Claude put 83.798 for the atomic mass for Krypton
-- Claude falsely listed group name for category identification
INSERT INTO Element VALUES (36, 'Krypton', 'Kr', 84.798, 18, 'Noble gas', 2, 4);
-- Claude put 85.468 for the atomic mass for Rubidium
INSERT INTO Element VALUES (37, 'Rubidium', 'Rb', 84.468, 1, 'Alkali metal', 1, 5);
INSERT INTO Element VALUES (38, 'Strontium', 'Sr', 87.62, 2, 'Alkaline earth metal', 1, 5);
INSERT INTO Element VALUES (39, 'Yttrium', 'Y', 88.906, 3, 'Transition metal', 1, 5);
INSERT INTO Element VALUES (40, 'Zirconium', 'Zr', 91.224, 4, 'Transition metal', 1, 5);
INSERT INTO Element VALUES (41, 'Niobium', 'Nb', 92.906, 5, 'Transition metal', 1, 5);
-- Claude put 95.96 for the atomic mass for Molybdenum
INSERT INTO Element VALUES (42, 'Molybdenum', 'Mo', 95.95, 6, 'Transition metal', 1, 5);
-- Claude put 98 for the atomic mass for Technetium
INSERT INTO Element VALUES (43, 'Technetium', 'Tc', 98.907, 7, 'Transition metal', 1, 5);
INSERT INTO Element VALUES (44, 'Ruthenium', 'Ru', 101.07, 8, 'Transition metal', 1, 5);
INSERT INTO Element VALUES (45, 'Rhodium', 'Rh', 102.906, 9, 'Transition metal', 1, 5);
INSERT INTO Element VALUES (46, 'Palladium', 'Pd', 106.42, 10, 'Transition metal', 1, 5);
INSERT INTO Element VALUES (47, 'Silver', 'Ag', 107.868, 11, 'Transition metal', 1, 5);
INSERT INTO Element VALUES (48, 'Cadmium', 'Cd', 112.411, 12, 'Transition metal', 1, 5);
INSERT INTO Element VALUES (49, 'Indium', 'In', 114.818, 13, 'Boron group, or, earth metal', 1, 5);
-- Claude put 118.710 for the atomic mass for Tin
INSERT INTO Element VALUES (50, 'Tin', 'Sn', 118.711, 14, 'Carbon group, or, tetrel', 1, 5);
INSERT INTO Element VALUES (51, 'Antimony', 'Sb', 121.760, 15, 'Nitrogen group, or, pnictogen', 3, 5);
INSERT INTO Element VALUES (52, 'Tellurium', 'Te', 127.6, 16, 'Oxygen group, or, chalcogen', 3, 5);
INSERT INTO Element VALUES (53, 'Iodine', 'I', 126.904, 17, 'Halogen', 2, 5);
-- Claude put 131.293 for the atomic mass for Xenon
-- Claude falsely listed group name for category identification
INSERT INTO Element VALUES (54, 'Xenon', 'Xe', 131.294, 18, 'Noble gas', 2, 5);
INSERT INTO Element VALUES (55, 'Cesium', 'Cs', 132.905, 1, 'Alkali metal', 1, 6);
-- Claude put 137.327 for the atomic mass for Barium
INSERT INTO Element VALUES (56, 'Barium', 'Ba', 137.328, 2, 'Alkaline earth metal', 1, 6);
INSERT INTO Element VALUES (57, 'Lanthanum', 'La', 138.905, 3, 'Lanthanide, or, inner transition element', 1, 6);
INSERT INTO Element VALUES (58, 'Cerium', 'Ce', 140.116, 3, 'Lanthanide, or, inner transition element', 1, 6);
INSERT INTO Element VALUES (59, 'Praseodymium', 'Pr', 140.908, 3, 'Lanthanide, or, inner transition element', 1, 6);
-- Claude put 144.242 for the atomic mass for Neodymium
INSERT INTO Element VALUES (60, 'Neodymium', 'Nd', 144.243, 3, 'Lanthanide, or, inner transition element', 1, 6);
-- Claude put 145 for the atomic mass for Promethium
INSERT INTO Element VALUES (61, 'Promethium', 'Pm', 144.913, 3, 'Lanthanide, or, inner transition element', 1, 6);
INSERT INTO Element VALUES (62, 'Samarium', 'Sm', 150.36, 3, 'Lanthanide, or, inner transition element', 1, 6);
INSERT INTO Element VALUES (63, 'Europium', 'Eu', 151.964, 3, 'Lanthanide, or, inner transition element', 1, 6);
INSERT INTO Element VALUES (64, 'Gadolinium', 'Gd', 157.25, 3, 'Lanthanide, or, inner transition element', 1, 6);
INSERT INTO Element VALUES (65, 'Terbium', 'Tb', 158.925, 3, 'Lanthanide, or, inner transition element', 1, 6);
INSERT INTO Element VALUES (66, 'Dysprosium', 'Dy', 162.500, 3, 'Lanthanide, or, inner transition element', 1, 6);
INSERT INTO Element VALUES (67, 'Holmium', 'Ho', 164.930, 3, 'Lanthanide, or, inner transition element', 1, 6);
INSERT INTO Element VALUES (68, 'Erbium', 'Er', 167.259, 3, 'Lanthanide, or, inner transition element', 1, 6);
INSERT INTO Element VALUES (69, 'Thulium', 'Tm', 168.934, 3, 'Lanthanide, or, inner transition element', 1, 6);
-- Claude put 173.054 for the atomic mass for Ytterbium
INSERT INTO Element VALUES (70, 'Ytterbium', 'Yb', 173.055, 3, 'Lanthanide, or, inner transition element', 1, 6);
INSERT INTO Element VALUES (71, 'Lutetium', 'Lu', 174.967, 3, 'Lanthanide, or, inner transition element', 1, 6);
INSERT INTO Element VALUES (72, 'Hafnium', 'Hf', 178.49, 4, 'Transition metal', 1, 6);
INSERT INTO Element VALUES (73, 'Tantalum', 'Ta', 180.948, 5, 'Transition metal', 1, 6);
INSERT INTO Element VALUES (74, 'Tungsten', 'W', 183.84, 6, 'Transition metal', 1, 6);
INSERT INTO Element VALUES (75, 'Rhenium', 'Re', 186.207, 7, 'Transition metal', 1, 6);
INSERT INTO Element VALUES (76, 'Osmium', 'Os', 190.23, 8, 'Transition metal', 1, 6);
INSERT INTO Element VALUES (77, 'Iridium', 'Ir', 192.217, 9, 'Transition metal', 1, 6);
-- Claude put 195.084 for the atomic mass for Platinum
INSERT INTO Element VALUES (78, 'Platinum', 'Pt', 195.085, 10, 'Transition metal', 1, 6);
INSERT INTO Element VALUES (79, 'Gold', 'Au', 196.967, 11, 'Transition metal', 1, 6);
INSERT INTO Element VALUES (80, 'Mercury', 'Hg', 200.592, 12, 'Transition metal', 1, 6);
INSERT INTO Element VALUES (81, 'Thallium', 'Tl', 204.383, 13, 'Boron group, or, earth metal', 1, 6);
INSERT INTO Element VALUES (82, 'Lead', 'Pb', 207.2, 14, 'Carbon group, or, tetrel', 1, 6);
INSERT INTO Element VALUES (83, 'Bismuth', 'Bi', 208.980, 15, 'Nitrogen group, or, pnictogen', 1, 6);
-- Claude put 209 for the atomic mass for Polonium
INSERT INTO Element VALUES (84, 'Polonium', 'Po', 208.982, 16, 'Oxygen group, or, chalcogen', 1, 6);
-- Claude put 210 for the atomic mass for Astatine
INSERT INTO Element VALUES (85, 'Astatine', 'At', 209.987, 17, 'Halogen', 3, 6);
-- Claude put 222 for the atomic mass for Radon
-- Claude falsely listed group name for category identification
INSERT INTO Element VALUES (86, 'Radon', 'Rn', 222.018, 18, 'Noble gas', 2, 6);
-- Claude put 223 for the atomic mass for Francium
INSERT INTO Element VALUES (87, 'Francium', 'Fr', 223.020, 1, 'Alkali metal', 1, 7);
-- Claude put 226 for the atomic mass for Radium
INSERT INTO Element VALUES (88, 'Radium', 'Ra', 226.025, 2, 'Alkaline earth metal', 1, 7);
-- Claude put 227 for the atomic mass for Actinium
INSERT INTO Element VALUES (89, 'Actinium', 'Ac', 227.028, 3, 'Actinide, or, inner transition element', 1, 7);
INSERT INTO Element VALUES (90, 'Thorium', 'Th', 232.038, 3, 'Actinide, or, inner transition element', 1, 7);
INSERT INTO Element VALUES (91, 'Protactinium', 'Pa', 231.036, 3, 'Actinide, or, inner transition element', 1, 7);
INSERT INTO Element VALUES (92, 'Uranium', 'U', 238.029, 3, 'Actinide, or, inner transition element', 1, 7);
-- Claude put 237 for the atomic mass for Neptunium
INSERT INTO Element VALUES (93, 'Neptunium', 'Np', 237.048, 3, 'Actinide, or, inner transition element', 1, 7);
-- Claude put 244 for the atomic mass for Plutonium
INSERT INTO Element VALUES (94, 'Plutonium', 'Pu', 244.064, 3, 'Actinide, or, inner transition element', 1, 7);
-- Claude put 243 for the atomic mass for Americium
INSERT INTO Element VALUES (95, 'Americium', 'Am', 243.061, 3, 'Actinide, or, inner transition element', 1, 7);
-- Claude put 247 for the atomic mass for Curium
INSERT INTO Element VALUES (96, 'Curium', 'Cm', 247.070, 3, 'Actinide, or, inner transition element', 1, 7);
-- Claude put 247 for the atomic mass for Berkelium
INSERT INTO Element VALUES (97, 'Berkelium', 'Bk', 247.070, 3, 'Actinide, or, inner transition element', 1, 7);
-- Claude put 251 for the atomic mass for Californium
INSERT INTO Element VALUES (98, 'Californium', 'Cf', 251.080, 3, 'Actinide, or, inner transition element', 1, 7);
-- Claude put 252 for the atomic mass for Einsteinium
INSERT INTO Element VALUES (99, 'Einsteinium', 'Es', 254, 3, 'Actinide, or, inner transition element', 1, 7);
-- Claude put 257 for the atomic mass for Fermium
INSERT INTO Element VALUES (100, 'Fermium', 'Fm', 257.095, 3, 'Actinide, or, inner transition element', 1, 7);
-- Claude put 258 for the atomic mass for Mendelevium
INSERT INTO Element VALUES (101, 'Mendelevium', 'Md', 258.1, 3, 'Actinide, or, inner transition element', 1, 7);
-- Claude put 259 for the atomic mass for Nobelium
INSERT INTO Element VALUES (102, 'Nobelium', 'No', 259.101, 3, 'Actinide, or, inner transition element', 1, 7);
-- Claude put 266 for the atomic mass for Lawrencium
INSERT INTO Element VALUES (103, 'Lawrencium', 'Lr', 262, 3, 'Actinide, or, inner transition element', 1, 7);
INSERT INTO Element VALUES (104, 'Rutherfordium', 'Rf', 267, 4, 'Transition metal', 1, 7);
-- Claude put 268 for the atomic mass for Dubnium
INSERT INTO Element VALUES (105, 'Dubnium', 'Db', 268.13, 5, 'Transition metal', 1, 7);
-- Claude put 269 for the atomic mass for Seaborgium
INSERT INTO Element VALUES (106, 'Seaborgium', 'Sg', 271.13, 6, 'Transition metal', 1, 7);
INSERT INTO Element VALUES (107, 'Bohrium', 'Bh', 270, 7, 'Transition metal', 1, 7);
-- Claude put 277 for the atomic mass for Hassium
INSERT INTO Element VALUES (108, 'Hassium', 'Hs', 277.15, 8, 'Transition metal', 1, 7);
-- Claude put 278 for the atomic mass for Meitnerium
INSERT INTO Element VALUES (109, 'Meitnerium', 'Mt', 276.15, 9, 'Transition metal', 1, 7);
-- Claude put 281 for the atomic mass for Darmstadtium
INSERT INTO Element VALUES (110, 'Darmstadtium', 'Ds', 281.16, 10, 'Transition metal', 1, 7);
-- Claude put 282 for the atomic mass for Roentgenium
INSERT INTO Element VALUES (111, 'Roentgenium', 'Rg', 280.16, 11, 'Transition metal', 1, 7);
-- Claude put 285 for the atomic mass for Copernicium
INSERT INTO Element VALUES (112, 'Copernicium', 'Cn', 285.17, 12, 'Transition metal', 1, 7);
INSERT INTO Element VALUES (113, 'Nihonium', 'Nh', 286, 13, 'Boron group, or, earth metal', 1, 7);
-- Claude put 289 for the atomic mass for Flerovium
INSERT INTO Element VALUES (114, 'Flerovium', 'Fl', 289.19, 14, 'Carbon group, or, tetrel', 1, 7);
INSERT INTO Element VALUES (115, 'Moscovium', 'Mc', 290, 15, 'Nitrogen group, or, pnictogen', 1, 7);
INSERT INTO Element VALUES (116, 'Livermorium', 'Lv', 293, 16, 'Oxygen group, or, chalcogen', 1, 7);
-- Claude mistakenly classified this as a Metalloid when it should have been a Metal
INSERT INTO Element VALUES (117, 'Tennessine', 'Ts', 294, 17, 'Halogen', 1, 7);
-- Claude had 'Metalloid' instead of 'Noble gas'
-- Claude mistakenly classified this as a Metalloid when it should have been a Metal
INSERT INTO Element VALUES (118, 'Oganesson', 'Og', 294, 18, 'Noble gas', 1, 7);

DROP TABLE Element;
DROP TABLE Category;
DROP TABLE Period;


-- Average atomic mass by category
SELECT c.category_name, AVG(e.atomic_mass) AS avg_atomic_mass
FROM Element e
JOIN Category c ON e.Category_category_id = c.category_id
GROUP BY c.category_name;

-- Count of elements per period
SELECT p.period_id, COUNT(e.atomic_number) AS element_count
FROM Element e
JOIN Period p ON e.Period_period_id = p.period_id
GROUP BY p.period_id
ORDER BY p.period_id;

/* Minimal goal: write queries to demonstrate calculations through aggregate functions */
-- The COUNT(*) function is introduced in the textbook on page 92
-- This query finds the count of elements per group
SELECT group_number, group_name, COUNT(*) AS element_count
FROM Element
GROUP BY group_number, group_name
ORDER BY group_number;

/* Due to the series of inner transition elements occupying group (i.e. column) 
   3 on the periodic table, a series which spans across 14 columns and is thus 
   displayed as two rows at the very bottom, the results of the previous query 
   showed duplicates in the group_number column. Therefore, to craft a more 
   advanced query which removes these duplicates, I prompted Claude to generate
   a more advanced query. Cladue used the "CASE" statement, something that was 
   mentioned in our textbook on pages 384-385. */
SELECT group_number,
       CASE WHEN group_name IN ('Lanthanide, or, inner transition element',
                                'Actinide, or, inner transition element')
            THEN 'Inner transition element'
            ELSE group_name
       END AS group_name,
       COUNT(*) AS element_count
FROM Element
GROUP BY group_number,
         CASE WHEN group_name IN ('Lanthanide, or, inner transition element',
                                  'Actinide, or, inner transition element')
              THEN 'Inner transition element'
              ELSE group_name
         END
ORDER BY group_number;

-- The MAX() and MIN() functions are introduced in the textbook on page 92
-- This query finds the maximum and minimum atomic mass per category
SELECT c.category_name,
       MAX(e.atomic_mass) AS "Max. Atomic Mass",
       MIN(e.atomic_mass) AS "Min. Atomic Mass"
FROM Element e
JOIN Category c ON e.Category_category_id = c.category_id
GROUP BY c.category_name;

-- Subquery: elements with atomic mass above the average
SELECT element_name, atomic_mass
FROM Element
WHERE atomic_mass > (SELECT AVG(atomic_mass) FROM Element) -- nested part runs first
ORDER BY atomic_mass;

-- View: element names with their category and period
CREATE VIEW Element_Summary AS
SELECT e.element_name, e.symbol, c.category_name, p.period_id
FROM Element e
JOIN Category c ON e.Category_category_id = c.category_id
JOIN Period p ON e.Period_period_id = p.period_id;
SELECT * FROM Element_Summary; -- access the view

-- Attempt to delete a category referenced by elements;
-- the foreign key constraint will prevent this
DELETE FROM Category WHERE category_id = 1;

-- Query demonstrating the category_description and number_of_electrons
-- attributes recommended by Mr. Dolphay
SELECT e.element_name, e.symbol, c.category_name, c.category_description,
       p.period_id, p.number_of_electrons
FROM Element e
JOIN Category c ON e.Category_category_id = c.category_id
JOIN Period p ON e.Period_period_id = p.period_id
WHERE e.atomic_number <= 10
ORDER BY e.atomic_number;

/*
Here is a good reference website:
https://ptable.com/#Properties
*/
