-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-03-15 19:48:36 CDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Category 
    ( 
     category_id VARCHAR2(50) 
                    
    ) 
;

ALTER TABLE Category 
    ADD CONSTRAINT Category_category_id_UN UNIQUE ( category_id ) ;
    
CREATE TABLE Element 
    ( 
     atomic_number        NUMBER 
                     NOT NULL , 
     element_name         VARCHAR2(100) 
                    , 
     symbol               VARCHAR2(10) 
                    , 
     atomic_mass          NUMBER 
                    , 
     period               NUMBER 
                    , 
     group_number         NUMBER 
                    , 
     category             VARCHAR2(50) 
                    , 
     Category_category_id VARCHAR2(50) 
                     NOT NULL , 
     Period_period_id     NUMBER 
                     NOT NULL 
    ) 
;

ALTER TABLE Element 
    ADD CONSTRAINT Element_PK PRIMARY KEY ( atomic_number ) ;
CREATE TABLE Period 
    ( 
     period_id NUMBER 
                    
    ) 
;

ALTER TABLE Period 
    ADD CONSTRAINT Period_period_id_UN UNIQUE ( period_id ) ;
    
ALTER TABLE Element 
    ADD CONSTRAINT Element_Category_FK FOREIGN KEY 
    ( 
     Category_category_id
    ) 
    REFERENCES Category 
    ( 
     category_id
    ) 
;

ALTER TABLE Element 
    ADD CONSTRAINT Element_Period_FK FOREIGN KEY 
    ( 
     Period_period_id
    ) 
    REFERENCES Period 
    ( 
     period_id
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                  11
-- WARNINGS                                 0