-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-03-15 19:48:36 CDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Category 
    ( 
     category_id VARCHAR2(50),
     category_name        VARCHAR2(100),
     category_description VARCHAR2(500)
                    
    ) 
;

ALTER TABLE Category 
    ADD CONSTRAINT Category_category_id_UN UNIQUE ( category_id ) ;
    
CREATE TABLE Element 
    ( 
     atomic_number        NUMBER 
                     NOT NULL , -- primary key
     element_name         VARCHAR2(100) 
                    , 
     symbol               VARCHAR2(10) 
                    , 
     atomic_mass          NUMBER 
                    , 
     period               NUMBER 
                    , 
     group_number         NUMBER -- groups indicate the vertical column
                    , 
     group_name           VARCHAR2(100)
                    , 
     Category_category_id VARCHAR2(50) -- this is a foreign key
                     NOT NULL , -- references Category table category_id column
     Period_period_id     NUMBER -- this is a foreign key
                     NOT NULL -- references Period table period_id column
    ) 
;

ALTER TABLE Element 
    ADD CONSTRAINT Element_PK PRIMARY KEY ( atomic_number ) ;
    
/* Period indicates the sequential filling of each electron orbital.
   Electrons fill from the lowest energy levels to highest ones.
   Elements in a Period have the same number of electron shells. */
CREATE TABLE Period -- horizontal rows
    ( 
     period_id NUMBER 
                    ,
     number_of_electrons  NUMBER -- number of electrons that occupy that period
    ) 
;

ALTER TABLE Period 
    ADD CONSTRAINT Period_period_id_UN UNIQUE ( period_id ) ;
    
ALTER TABLE Element 
    ADD CONSTRAINT Element_Category_FK FOREIGN KEY 
    ( 
     Category_category_id
    ) 
    REFERENCES Category 
    ( 
     category_id
    ) 
;

ALTER TABLE Element 
    ADD CONSTRAINT Element_Period_FK FOREIGN KEY 
    ( 
     Period_period_id
    ) 
    REFERENCES Period 
    ( 
     period_id
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                  11
-- WARNINGS                                 0

INSERT INTO Category VALUES ('Metal', '', '');
INSERT INTO Category VALUES ('Nonmetal', '', '');
INSERT INTO Category VALUES ('Noble Gas', '', '');
INSERT INTO Category VALUES ('Metalloid', '', '');

INSERT INTO Period VALUES (1, '');
INSERT INTO Period VALUES (2, '');
INSERT INTO Period VALUES (3, '');
INSERT INTO Period VALUES (4, '');
INSERT INTO Period VALUES (5, '');
INSERT INTO Period VALUES (6, '');
INSERT INTO Period VALUES (7, '');

/* Used Claude for defining data in these INSERT statements, 
   then I double checked the data for myself. */

-- atomic_number, element_name, symbol, atomic_mass, period, group_number,
-- group_name, Category_category_id, Period_period_id
INSERT INTO Element VALUES (1, 'Hydrogen', 'H', 1.008, 1, 1, 'Nonmetal', 'Nonmetal', 1);
INSERT INTO Element VALUES (2, 'Helium', 'He', 4.003, 1, 18, 'Noble Gas', 'Noble Gas', 1);
INSERT INTO Element VALUES (3, 'Lithium', 'Li', 6.941, 2, 1, 'Metal', 'Metal', 2);
INSERT INTO Element VALUES (4, 'Beryllium', 'Be', 9.012, 2, 2, 'Metal', 'Metal', 2);
INSERT INTO Element VALUES (5, 'Boron', 'B', 10.811, 2, 13, 'Metalloid', 'Metalloid', 2);
INSERT INTO Element VALUES (6, 'Carbon', 'C', 12.011, 2, 14, 'Nonmetal', 'Nonmetal', 2);
INSERT INTO Element VALUES (7, 'Nitrogen', 'N', 14.007, 2, 15, 'Nonmetal', 'Nonmetal', 2);
INSERT INTO Element VALUES (8, 'Oxygen', 'O', 15.999, 2, 16, 'Nonmetal', 'Nonmetal', 2);
INSERT INTO Element VALUES (9, 'Fluorine', 'F', 18.998, 2, 17, 'Nonmetal', 'Nonmetal', 2);
INSERT INTO Element VALUES (10, 'Neon', 'Ne', 20.180, 2, 18, 'Noble Gas', 'Noble Gas', 2);
INSERT INTO Element VALUES (11, 'Sodium', 'Na', 22.990, 3, 1, 'Metal', 'Metal', 3);
INSERT INTO Element VALUES (12, 'Magnesium', 'Mg', 24.305, 3, 2, 'Metal', 'Metal', 3);
INSERT INTO Element VALUES (13, 'Aluminum', 'Al', 26.982, 3, 13, 'Metal', 'Metal', 3);
INSERT INTO Element VALUES (14, 'Silicon', 'Si', 28.086, 3, 14, 'Metalloid', 'Metalloid', 3);
INSERT INTO Element VALUES (15, 'Phosphorus', 'P', 30.974, 3, 15, 'Nonmetal', 'Nonmetal', 3);
INSERT INTO Element VALUES (16, 'Sulfur', 'S', 32.065, 3, 16, 'Nonmetal', 'Nonmetal', 3);
INSERT INTO Element VALUES (17, 'Chlorine', 'Cl', 35.453, 3, 17, 'Nonmetal', 'Nonmetal', 3);
INSERT INTO Element VALUES (18, 'Argon', 'Ar', 39.948, 3, 18, 'Noble Gas', 'Noble Gas', 3);
INSERT INTO Element VALUES (19, 'Potassium', 'K', 39.098, 4, 1, 'Metal', 'Metal', 4);
INSERT INTO Element VALUES (20, 'Calcium', 'Ca', 40.078, 4, 2, 'Metal', 'Metal', 4);
INSERT INTO Element VALUES (21, 'Scandium', 'Sc', 44.956, 4, 3, 'Metal', 'Metal', 4);
INSERT INTO Element VALUES (22, 'Titanium', 'Ti', 47.867, 4, 4, 'Metal', 'Metal', 4);
INSERT INTO Element VALUES (23, 'Vanadium', 'V', 50.942, 4, 5, 'Metal', 'Metal', 4);
INSERT INTO Element VALUES (24, 'Chromium', 'Cr', 51.996, 4, 6, 'Metal', 'Metal', 4);
INSERT INTO Element VALUES (25, 'Manganese', 'Mn', 54.938, 4, 7, 'Metal', 'Metal', 4);
INSERT INTO Element VALUES (26, 'Iron', 'Fe', 55.845, 4, 8, 'Metal', 'Metal', 4);
INSERT INTO Element VALUES (27, 'Cobalt', 'Co', 58.933, 4, 9, 'Metal', 'Metal', 4);
INSERT INTO Element VALUES (28, 'Nickel', 'Ni', 58.693, 4, 10, 'Metal', 'Metal', 4);
INSERT INTO Element VALUES (29, 'Copper', 'Cu', 63.546, 4, 11, 'Metal', 'Metal', 4);
INSERT INTO Element VALUES (30, 'Zinc', 'Zn', 65.38, 4, 12, 'Metal', 'Metal', 4);
INSERT INTO Element VALUES (31, 'Gallium', 'Ga', 69.723, 4, 13, 'Metal', 'Metal', 4);
INSERT INTO Element VALUES (32, 'Germanium', 'Ge', 72.630, 4, 14, 'Metalloid', 'Metalloid', 4);
INSERT INTO Element VALUES (33, 'Arsenic', 'As', 74.922, 4, 15, 'Metalloid', 'Metalloid', 4);
INSERT INTO Element VALUES (34, 'Selenium', 'Se', 78.971, 4, 16, 'Nonmetal', 'Nonmetal', 4);
INSERT INTO Element VALUES (35, 'Bromine', 'Br', 79.904, 4, 17, 'Nonmetal', 'Nonmetal', 4);
INSERT INTO Element VALUES (36, 'Krypton', 'Kr', 83.798, 4, 18, 'Noble Gas', 'Noble Gas', 4);
INSERT INTO Element VALUES (37, 'Rubidium', 'Rb', 85.468, 5, 1, 'Metal', 'Metal', 5);
INSERT INTO Element VALUES (38, 'Strontium', 'Sr', 87.62, 5, 2, 'Metal', 'Metal', 5);
INSERT INTO Element VALUES (39, 'Yttrium', 'Y', 88.906, 5, 3, 'Metal', 'Metal', 5);
INSERT INTO Element VALUES (40, 'Zirconium', 'Zr', 91.224, 5, 4, 'Metal', 'Metal', 5);
INSERT INTO Element VALUES (41, 'Niobium', 'Nb', 92.906, 5, 5, 'Metal', 'Metal', 5);
INSERT INTO Element VALUES (42, 'Molybdenum', 'Mo', 95.96, 5, 6, 'Metal', 'Metal', 5);
INSERT INTO Element VALUES (43, 'Technetium', 'Tc', 98, 5, 7, 'Metal', 'Metal', 5);
INSERT INTO Element VALUES (44, 'Ruthenium', 'Ru', 101.07, 5, 8, 'Metal', 'Metal', 5);
INSERT INTO Element VALUES (45, 'Rhodium', 'Rh', 102.906, 5, 9, 'Metal', 'Metal', 5);
INSERT INTO Element VALUES (46, 'Palladium', 'Pd', 106.42, 5, 10, 'Metal', 'Metal', 5);
INSERT INTO Element VALUES (47, 'Silver', 'Ag', 107.868, 5, 11, 'Metal', 'Metal', 5);
INSERT INTO Element VALUES (48, 'Cadmium', 'Cd', 112.411, 5, 12, 'Metal', 'Metal', 5);
INSERT INTO Element VALUES (49, 'Indium', 'In', 114.818, 5, 13, 'Metal', 'Metal', 5);
INSERT INTO Element VALUES (50, 'Tin', 'Sn', 118.710, 5, 14, 'Metal', 'Metal', 5);
INSERT INTO Element VALUES (51, 'Antimony', 'Sb', 121.760, 5, 15, 'Metalloid', 'Metalloid', 5);
INSERT INTO Element VALUES (52, 'Tellurium', 'Te', 127.60, 5, 16, 'Metalloid', 'Metalloid', 5);
INSERT INTO Element VALUES (53, 'Iodine', 'I', 126.904, 5, 17, 'Nonmetal', 'Nonmetal', 5);
INSERT INTO Element VALUES (54, 'Xenon', 'Xe', 131.293, 5, 18, 'Noble Gas', 'Noble Gas', 5);
INSERT INTO Element VALUES (55, 'Cesium', 'Cs', 132.905, 6, 1, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (56, 'Barium', 'Ba', 137.327, 6, 2, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (57, 'Lanthanum', 'La', 138.905, 6, 3, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (58, 'Cerium', 'Ce', 140.116, 6, 3, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (59, 'Praseodymium', 'Pr', 140.908, 6, 3, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (60, 'Neodymium', 'Nd', 144.242, 6, 3, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (61, 'Promethium', 'Pm', 145, 6, 3, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (62, 'Samarium', 'Sm', 150.36, 6, 3, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (63, 'Europium', 'Eu', 151.964, 6, 3, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (64, 'Gadolinium', 'Gd', 157.25, 6, 3, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (65, 'Terbium', 'Tb', 158.925, 6, 3, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (66, 'Dysprosium', 'Dy', 162.500, 6, 3, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (67, 'Holmium', 'Ho', 164.930, 6, 3, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (68, 'Erbium', 'Er', 167.259, 6, 3, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (69, 'Thulium', 'Tm', 168.934, 6, 3, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (70, 'Ytterbium', 'Yb', 173.054, 6, 3, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (71, 'Lutetium', 'Lu', 174.967, 6, 3, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (72, 'Hafnium', 'Hf', 178.49, 6, 4, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (73, 'Tantalum', 'Ta', 180.948, 6, 5, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (74, 'Tungsten', 'W', 183.84, 6, 6, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (75, 'Rhenium', 'Re', 186.207, 6, 7, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (76, 'Osmium', 'Os', 190.23, 6, 8, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (77, 'Iridium', 'Ir', 192.217, 6, 9, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (78, 'Platinum', 'Pt', 195.084, 6, 10, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (79, 'Gold', 'Au', 196.967, 6, 11, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (80, 'Mercury', 'Hg', 200.592, 6, 12, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (81, 'Thallium', 'Tl', 204.383, 6, 13, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (82, 'Lead', 'Pb', 207.2, 6, 14, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (83, 'Bismuth', 'Bi', 208.980, 6, 15, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (84, 'Polonium', 'Po', 209, 6, 16, 'Metal', 'Metal', 6);
INSERT INTO Element VALUES (85, 'Astatine', 'At', 210, 6, 17, 'Metalloid', 'Metalloid', 6);
INSERT INTO Element VALUES (86, 'Radon', 'Rn', 222, 6, 18, 'Noble Gas', 'Noble Gas', 6);
INSERT INTO Element VALUES (87, 'Francium', 'Fr', 223, 7, 1, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (88, 'Radium', 'Ra', 226, 7, 2, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (89, 'Actinium', 'Ac', 227, 7, 3, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (90, 'Thorium', 'Th', 232.038, 7, 3, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (91, 'Protactinium', 'Pa', 231.036, 7, 3, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (92, 'Uranium', 'U', 238.029, 7, 3, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (93, 'Neptunium', 'Np', 237, 7, 3, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (94, 'Plutonium', 'Pu', 244, 7, 3, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (95, 'Americium', 'Am', 243, 7, 3, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (96, 'Curium', 'Cm', 247, 7, 3, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (97, 'Berkelium', 'Bk', 247, 7, 3, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (98, 'Californium', 'Cf', 251, 7, 3, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (99, 'Einsteinium', 'Es', 252, 7, 3, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (100, 'Fermium', 'Fm', 257, 7, 3, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (101, 'Mendelevium', 'Md', 258, 7, 3, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (102, 'Nobelium', 'No', 259, 7, 3, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (103, 'Lawrencium', 'Lr', 266, 7, 3, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (104, 'Rutherfordium', 'Rf', 267, 7, 4, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (105, 'Dubnium', 'Db', 268, 7, 5, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (106, 'Seaborgium', 'Sg', 269, 7, 6, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (107, 'Bohrium', 'Bh', 270, 7, 7, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (108, 'Hassium', 'Hs', 277, 7, 8, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (109, 'Meitnerium', 'Mt', 278, 7, 9, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (110, 'Darmstadtium', 'Ds', 281, 7, 10, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (111, 'Roentgenium', 'Rg', 282, 7, 11, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (112, 'Copernicium', 'Cn', 285, 7, 12, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (113, 'Nihonium', 'Nh', 286, 7, 13, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (114, 'Flerovium', 'Fl', 289, 7, 14, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (115, 'Moscovium', 'Mc', 290, 7, 15, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (116, 'Livermorium', 'Lv', 293, 7, 16, 'Metal', 'Metal', 7);
INSERT INTO Element VALUES (117, 'Tennessine', 'Ts', 294, 7, 17, 'Metalloid', 'Metalloid', 7);
INSERT INTO Element VALUES (118, 'Oganesson', 'Og', 294, 7, 18, 'Metalloid', 'Metalloid', 7);

-- SELECT statement with a JOIN
-- New Style Explicit JOIN
SELECT e.atomic_number, e.element_name, e.symbol, e.atomic_mass,
       e.group_number, c.category_id, p.period_id
FROM Element e
JOIN Category c ON e.Category_category_id = c.category_id
JOIN Period p ON e.Period_period_id = p.period_id;

-- UPDATE statement
UPDATE Element
SET atomic_mass = 1.008
WHERE atomic_number = 1;

-- DELETE prevented by a foreign key constraint
DELETE FROM Category
WHERE category_id = 'Metal';

-- CREATE VIEW statement
-- Used Claude to help me write the CREATE VIEW query
CREATE VIEW Element_Category_View AS
SELECT e.element_name, e.symbol, e.atomic_number, c.category_id
FROM Element e
JOIN Category c ON e.Category_category_id = c.category_id;

-- ALTER TABLE statement
ALTER TABLE Element
ADD discovery_year NUMBER;